import { getDb } from "./db.js";
import { topic, documentTopic, document } from "./schema.js";
import { and, eq, inArray } from "drizzle-orm";
import { hybridSearch } from "./search.js";
import { chatJSON } from "./ai/openrouter.js";

/**
 * Builds the system and user prompts instructing the model to generate a quiz
 * grounded only in the provided context chunks.
 *
 * @param {Object} params
 * @param {Array<{ content: string }>} params.contextChunks
 * @param {string} params.difficulty - easy, medium, hard
 * @param {number} params.count - number of questions
 * @param {string[]} params.topicNames - names of the topics
 * @returns {{ system: string, user: string }}
 */
export function buildGenerationPrompt({ contextChunks, difficulty, count, topicNames }) {
  const topicsStr = topicNames && topicNames.length > 0 ? topicNames.join(", ") : "general topics";
  const contextText = contextChunks.map((c, i) => `[Context Chunk ${i + 1}]:\n${c.content}`).join("\n\n");

  const system = `You are an expert educator. Your task is to generate exactly ${count} multiple-choice questions at "${difficulty}" difficulty level based on the provided context.
The questions must be grounded ONLY in the provided context. Do NOT invent facts or use outside knowledge.
The topics or subjects related to these questions are: ${topicsStr}.

Each question in your output MUST strictly follow this JSON structure:
{
  "question": "The question text",
  "options": [
    "Option A",
    "Option B",
    "Option C",
    "Option D"
  ],
  "answer": "Option B", // MUST match one of the elements in the options array EXACTLY
  "explanation": "A short explanation of why the answer is correct based on the context"
}

Output rules (follow exactly):
- Return ONLY a raw JSON array containing exactly ${count} question objects — nothing else.
- Do NOT wrap the array in markdown code fences and do NOT add any prose before or after it.
- Each question must have exactly 4 options.
- The 'answer' string must be exactly identical to one of the options.
- The questions must be factual, direct, and fully supported by the provided context chunks.`;

  const user = `Generate exactly ${count} multiple-choice questions at "${difficulty}" difficulty level from the following context:

--- START OF CONTEXT ---
${contextText}
--- END OF CONTEXT ---`;

  return { system, user };
}

/**
 * Parses and validates questions generated by the model.
 *
 * @param {any} raw - Raw output parsed from the model
 * @param {Object} options
 * @param {number} options.count - Desired number of questions
 * @returns {Array<{ question: string, options: string[], answer: string, explanation: string }>} Validated questions
 */
export function validateQuestions(raw, { count }) {
  let list = [];
  if (Array.isArray(raw)) {
    list = raw;
  } else if (raw && typeof raw === 'object' && Array.isArray(raw.questions)) {
    list = raw.questions;
  } else {
    return [];
  }

  const validQuestions = [];
  const seenQuestions = new Set();

  for (const item of list) {
    if (!item || typeof item !== 'object') continue;

    const questionText = typeof item.question === 'string' ? item.question.trim() : '';
    if (!questionText) continue;

    if (!Array.isArray(item.options) || item.options.length !== 4) continue;

    const options = item.options.map(opt => (typeof opt === 'string' ? opt.trim() : ''));
    if (options.some(opt => !opt)) continue;

    const uniqueOptions = new Set(options);
    if (uniqueOptions.size !== 4) continue;

    const answer = typeof item.answer === 'string' ? item.answer.trim() : '';
    if (!answer) continue;
    if (!options.includes(answer)) continue;

    const explanation = typeof item.explanation === 'string' ? item.explanation.trim() : '';
    const finalExplanation = explanation || 'No explanation provided.';

    const lowerQuestion = questionText.toLowerCase();
    if (seenQuestions.has(lowerQuestion)) continue;
    seenQuestions.add(lowerQuestion);

    // Trim/cap lengths defensively
    const cleanQuestion = questionText.slice(0, 1000);
    const cleanOptions = options.map(opt => opt.slice(0, 500));
    const cleanAnswer = cleanOptions[options.indexOf(answer)];
    const cleanExplanation = finalExplanation.slice(0, 2000);

    validQuestions.push({
      question: cleanQuestion,
      options: cleanOptions,
      answer: cleanAnswer,
      explanation: cleanExplanation
    });
  }

  return validQuestions.slice(0, count);
}

/**
 * Retrieves context chunks and orchestrates AI call to generate a quiz.
 *
 * @param {Record<string, any>} env - Cloudflare platform env object
 * @param {Object} params
 * @param {string} params.userId
 * @param {string[]} params.topicIds
 * @param {string} params.difficulty - easy, medium, hard
 * @param {number} params.count - requested question count
 * @returns {Promise<Object>} Quiz response details
 */
export async function generateQuiz(env, { userId, topicIds, difficulty, count }) {
  // 1. Validate inputs
  if (!['easy', 'medium', 'hard'].includes(difficulty)) {
    throw new Error("Invalid difficulty. Must be easy, medium, or hard.");
  }

  const clampedCount = Math.max(1, Math.min(20, Math.floor(Number(count) || 5)));

  if (!Array.isArray(topicIds) || topicIds.length === 0) {
    throw new Error("topicIds must be a non-empty array.");
  }

  const db = getDb(env);

  // Select only topics owned by the user
  const ownedTopics = await db.select()
    .from(topic)
    .where(
      and(
        eq(topic.userId, userId),
        inArray(topic.id, topicIds)
      )
    );

  if (ownedTopics.length === 0) {
    return {
      questions: [],
      topicNames: [],
      difficulty,
      requestedCount: clampedCount,
      generatedCount: 0,
      sourceDocumentIds: [],
      reason: "No owned topics found."
    };
  }

  // 2. Fetch linked ready documents and perform hybridSearch for each topic
  const seenChunkIds = new Set();
  const aggregatedChunks = [];

  for (const topicObj of ownedTopics) {
    const docTopics = await db.select({ documentId: documentTopic.documentId })
      .from(documentTopic)
      .innerJoin(document, eq(documentTopic.documentId, document.id))
      .where(
        and(
          eq(documentTopic.topicId, topicObj.id),
          eq(document.status, "ready"),
          eq(document.userId, userId)
        )
      );

    const documentIds = docTopics.map(dt => dt.documentId);
    if (documentIds.length === 0) {
      continue;
    }

    const chunks = await hybridSearch(env, {
      userId,
      query: topicObj.name,
      documentIds,
      topK: 8
    });

    for (const chunkItem of chunks) {
      if (!seenChunkIds.has(chunkItem.chunkId)) {
        seenChunkIds.add(chunkItem.chunkId);
        aggregatedChunks.push(chunkItem);
      }
    }
  }

  // 3. structured empty result if no context found
  if (aggregatedChunks.length === 0) {
    return {
      questions: [],
      topicNames: ownedTopics.map(t => t.name),
      difficulty,
      requestedCount: clampedCount,
      generatedCount: 0,
      sourceDocumentIds: [],
      reason: "No content chunks found for the selected topics."
    };
  }

  // Cap total context chunks to fit window limits (e.g. 20 chunks, max 25,000 characters)
  let totalChars = 0;
  const cappedChunks = [];
  const finalSourceDocIds = new Set();

  for (const chunkItem of aggregatedChunks) {
    if (cappedChunks.length >= 20) break;
    if (totalChars + chunkItem.content.length > 25000) break;
    cappedChunks.push(chunkItem);
    totalChars += chunkItem.content.length;
    finalSourceDocIds.add(chunkItem.documentId);
  }

  // 4. Build prompt and run OpenRouter chatJSON call
  const topicNames = ownedTopics.map(t => t.name);
  const { system, user } = buildGenerationPrompt({
    contextChunks: cappedChunks,
    difficulty,
    count: clampedCount,
    topicNames
  });

  const schema = {
    type: 'object',
    properties: {
      questions: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            question: { type: 'string' },
            options: {
              type: 'array',
              items: { type: 'string' },
              minItems: 4,
              maxItems: 4
            },
            answer: { type: 'string' },
            explanation: { type: 'string' }
          },
          required: ['question', 'options', 'answer', 'explanation']
        }
      }
    },
    required: ['questions']
  };

  let rawResponse;
  try {
    rawResponse = await chatJSON(env, { system, user, schema });
  } catch (err) {
    console.error("[Quiz Generation] AI generation failed:", err);
    throw new Error(`AI generation failed: ${err.message}`);
  }

  let questions = validateQuestions(rawResponse, { count: clampedCount });

  // Optional: perform one retry/topping-up call if we got fewer questions than requested
  if (questions.length < clampedCount) {
    const missingCount = clampedCount - questions.length;
    const retryPrompt = buildGenerationPrompt({
      contextChunks: cappedChunks,
      difficulty,
      count: missingCount,
      topicNames
    });

    const existingQuestionsText = questions.map(q => q.question).join("\n");
    const modifiedUserPrompt = `${retryPrompt.user}\n\nIMPORTANT: Do NOT generate any of the following questions, as they already exist:\n${existingQuestionsText}`;

    try {
      const retryResponse = await chatJSON(env, {
        system: retryPrompt.system,
        user: modifiedUserPrompt,
        schema
      });
      const retryQuestions = validateQuestions(retryResponse, { count: missingCount });

      const existingSet = new Set(questions.map(q => q.question.toLowerCase()));
      for (const q of retryQuestions) {
        if (!existingSet.has(q.question.toLowerCase())) {
          questions.push(q);
          existingSet.add(q.question.toLowerCase());
        }
      }
    } catch (retryErr) {
      console.warn("[Quiz Generation] Topping up retry failed:", retryErr);
    }
  }

  questions = questions.slice(0, clampedCount);

  return {
    questions,
    topicNames,
    difficulty,
    requestedCount: clampedCount,
    generatedCount: questions.length,
    sourceDocumentIds: Array.from(finalSourceDocIds)
  };
}
